name: Maintain staging branch

on:
  pull_request:
    types:  # Triggers when a PR is closed (merged or not)
      - labeled
      - unlabeled
      - closed
      - synchronize
jobs:
  maintain_staging:
    if: (contains(github.event.pull_request.labels.name, 'staging')) || (github.event.action == 'closed' && github.event.pull_request.merged) || (github.event.label.name == 'Staging')
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Step 2: Reset staging branch to match main
      - name: Reset staging to main
        uses: ./.github/actions/action_name
