name: Maintain staging branch

on:
  pull_request:
    types:  # Triggers when a PR is closed (merged or not)
      - labeled
jobs:
  maintain_staging:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2
      # Step 2: Reset staging branch to match main
      - name: Reset staging to main
        uses: ./.github/actions/action_name
